import Footer from '@/components/Footer';
import Header from '@/components/Header';
import axios from 'axios';
import Head from 'next/head';

export default function Home({ country }) {
  return (
    <>
      <Head>
        <title>Shoppers</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="">
        <Header country={country} />
        <main className="px-4 m-auto">
          <h2>Main</h2>
        </main>
        <Footer country={country} />
      </div>
    </>
  );
}

export async function getServerSideProps() {
  let data = await axios
    .get('https://api.ipregistry.co/?key=9mbtdmyh518jtkno')
    .then((res) => {
      return res.data.location.country;
    })
    .catch((err) => {
      console.log(err);
    });
  return {
    props: {
      country: { name: 'Bangladesh', flag: data.flag.emojitwo },
    },
  };
}
