import Footer from '@/components/Footer';
import Header from '@/components/Header';
import Head from 'next/head';

export default function Home() {
  return (
    <>
      <Head>
        <title>Shoppers</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="">
        <Header />
        <main className="px-4 m-auto">
          <h2>Main</h2>
        </main>
        <Footer />
      </div>
    </>
  );
}
